server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  application:
    name: resource-server
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/data_test/data
    driverClassName: org.h2.Driver
    username: sa
    password: test 
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false          
